exclude_dirs:
  - .venv
  - __pycache__
  - submodules

skips:
  - B101   # assert used
  - B311   # standard pseudo-random (random module)
  - B404   # subprocess without shell=False
  - B603   # subprocess with shell=True
  - B607   # start process with partial path
  - B615   # huggingface unsafe download (false positive for local models)

severity: medium
confidence: medium

targets:
  - src
  - test