[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false
skip-magic-trailing-comma = false
include = '\.pyi?$'
exclude = '''
/(
  \.git
  | \.venv
  | __pycache__
  | submodules
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
skip_gitignore = true
known_first_party = ["src"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true

# Specific ignores for transformers
[[tool.mypy.overrides]]
module = [
    "transformers",
    "transformers.*",
    "trl",
    "trl.*",
    "datasets",
    "datasets.*",
    "wandb",
    "wandb.*"
]
ignore_missing_imports = true